import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Footer from "@/components/main/Footer";
import { ReactNode } from "react";
import Providers from "./providers";
import { Toaster } from "@/components/ui/sonner";
import NoonRefresher from "@/components/NoonRefresher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "UUSangJong",
  description: "Generated by create next app",
  icons: {
    icon: "/logos/logo_black_circle.png",
    shortcut: "/logos/logo_black_circle.png",
    apple: "/logos/logo_black_circle.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <Toaster richColors />
          <NoonRefresher />
          {children}
        </Providers>
      </body>
    </html>
  );
}
