import type { Metadata } from "next";
import "../globals.css";
import AppHeader from "@/components/common/AppHeader";
import Footer from "@/components/main/Footer";
import { Fragment } from "react";

export const metadata: Metadata = {
  title: "UUSangJong",
  description: "Generated by create next app",
  icons: {
    icon: "/logos/logo_black_circle.png",
    shortcut: "/logos/logo_black_circle.png",
    apple: "/logos/logo_black_circle.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Fragment>
      <AppHeader />
      {children}
      <Footer />
    </Fragment>
  );
}
